### ISSUE TITLE
Optional price suggestion

### ISSUE THREAD

**Issue by PixelPog** [devmount/wishlist#7]
I've got a request from a friend to add an optional price suggestion. It would be very helpful if the user gets a quick overview of the prices from the presents. Maybe its visible as addition at the end of the title separated with brackets or another sign. So you do not have to click through everything in order to geht this information. I would be happy if you would consider this idea ;) Thanks a lot!

**Comment by devmount** [comment]
Great suggestion! Will be part of the next release.

**Comment by devmount** [comment]
@PixelPog This is now implemented with #8. Let me know if it works or if you need anything else.

**Comment by PixelPog** [comment]
@devmount Nice its really great! It works perfectly. Thanks a lot for the fast implementation 💪
